// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.22.3
// source: payment/payment.proto

package payment

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	TransferService_TransferPayments_FullMethodName = "/payment.TransferService/TransferPayments"
)

// TransferServiceClient is the client API for TransferService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransferServiceClient interface {
	TransferPayments(ctx context.Context, opts ...grpc.CallOption) (TransferService_TransferPaymentsClient, error)
}

type transferServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTransferServiceClient(cc grpc.ClientConnInterface) TransferServiceClient {
	return &transferServiceClient{cc}
}

func (c *transferServiceClient) TransferPayments(ctx context.Context, opts ...grpc.CallOption) (TransferService_TransferPaymentsClient, error) {
	stream, err := c.cc.NewStream(ctx, &TransferService_ServiceDesc.Streams[0], TransferService_TransferPayments_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &transferServiceTransferPaymentsClient{stream}
	return x, nil
}

type TransferService_TransferPaymentsClient interface {
	Send(*Payment) error
	CloseAndRecv() (*emptypb.Empty, error)
	grpc.ClientStream
}

type transferServiceTransferPaymentsClient struct {
	grpc.ClientStream
}

func (x *transferServiceTransferPaymentsClient) Send(m *Payment) error {
	return x.ClientStream.SendMsg(m)
}

func (x *transferServiceTransferPaymentsClient) CloseAndRecv() (*emptypb.Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(emptypb.Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TransferServiceServer is the server API for TransferService service.
// All implementations must embed UnimplementedTransferServiceServer
// for forward compatibility
type TransferServiceServer interface {
	TransferPayments(TransferService_TransferPaymentsServer) error
	mustEmbedUnimplementedTransferServiceServer()
}

// UnimplementedTransferServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTransferServiceServer struct {
}

func (UnimplementedTransferServiceServer) TransferPayments(TransferService_TransferPaymentsServer) error {
	return status.Errorf(codes.Unimplemented, "method TransferPayments not implemented")
}
func (UnimplementedTransferServiceServer) mustEmbedUnimplementedTransferServiceServer() {}

// UnsafeTransferServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransferServiceServer will
// result in compilation errors.
type UnsafeTransferServiceServer interface {
	mustEmbedUnimplementedTransferServiceServer()
}

func RegisterTransferServiceServer(s grpc.ServiceRegistrar, srv TransferServiceServer) {
	s.RegisterService(&TransferService_ServiceDesc, srv)
}

func _TransferService_TransferPayments_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TransferServiceServer).TransferPayments(&transferServiceTransferPaymentsServer{stream})
}

type TransferService_TransferPaymentsServer interface {
	SendAndClose(*emptypb.Empty) error
	Recv() (*Payment, error)
	grpc.ServerStream
}

type transferServiceTransferPaymentsServer struct {
	grpc.ServerStream
}

func (x *transferServiceTransferPaymentsServer) SendAndClose(m *emptypb.Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *transferServiceTransferPaymentsServer) Recv() (*Payment, error) {
	m := new(Payment)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TransferService_ServiceDesc is the grpc.ServiceDesc for TransferService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransferService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payment.TransferService",
	HandlerType: (*TransferServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TransferPayments",
			Handler:       _TransferService_TransferPayments_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "payment/payment.proto",
}
